### ISSUE TITLE
Distorted Audio in 1.0.0

### ISSUE THREAD

**Issue by mattclaw** [danielkraak/GC-Loader#1] opened 2020-01-09 06:05 UTC
Thanks for the great product. I've actually spent the past 2-3 years searching for NOS GCN ODEs, so when I found your thread on gc-forever I was so excited by the prospect of you shipping. What a nice surprise that you were able to partner with Dan to launch the GC-Loader! I'm loving it so far and I've only had it installed ~24 hours.

I updated GC-Loader tonight to `1.0.0` and played a few games. Of the three I played, I had two instances of glitchy background music where the audio was distorted and noisy for a brief period, but overall effects and background music sounded fine throughout the rest of the games' sessions. The 3rd game, Chibi Robo, exhibited no issues during my ~30 minutes of play.

In _Wave Race - Blue Storm (USA)_, I have been able to reproduce this between cold boot at the character select screen of the "Free Ride" mode. The first time I encountered it was while scrolling from the 1st character to the 2nd character (David Mariner) in the list; the initial playback of his background music was corrupted, but after changing to another character and back, subsequent playback of the audio was fine. After turning the system off and back on, booting into the game, and returning to that screen, it took me a minute or so to reproduce the distortion by erratically cycling through characters.

The other affected game was _Super Monkey Ball (USA)_ which had glitched audio after completing the 10 beginner levels when it plays a celebratory sequence. I've not yet had a chance to attempt to replicate this instance. However, the corruption in the audio was similar in nature to that found in Wave Race.

> DOL-001
> NTSC Revision 1.1
> GCVideo Dual v2.4b installed
> Connected to OSSC through Insurrection RGB SCART cable.
> Samsung 128GB (U3) microSD card

> Swiss r756 was used to boot all titles
> All ISOs were trimmed with NKit v1.4 and have been verified to be known good dumps against a popular database.

I only just installed the GC-Loader late last night, so I hadn't put much time in on the previous version and only played these 3 games tonight. I'll update this issue if I encounter others.

**Comment by danielkraak** [comment] 2020-01-09 08:22
Thanks for reporting the issue. I will look into it.

**Comment by fille1976** [comment] 2020-01-11 23:21
Tested with swiss r766 on a pal dol 001 gamecube with gcloader,still no streaming audio,i'm on latest firmware with gcloader.

**Comment by danielkraak** [comment] 2020-01-13 09:53
Could you explain more specifically what you mean with 'no streaming audio'? Are you encountering issues with certain games? Or all games?

**Comment by fille1976** [comment] 2020-01-13 11:02
Hi,

I will explain after work.
Grts filip

Verstuurd vanaf mijn iPhone

**Comment by fille1976** [comment] 2020-01-13 11:13
In wave race and star fox i don’t get sound in the intro,but i gona test more,i left the patches normal in swiss,tonight i gona get a better view on it.

Verstuurd vanaf mijn iPhone

**Comment by fille1976** [comment] 2020-01-13 17:06
Testing Eternal Darkness,that seems to work fine.
Will test some more audio streaming games and report here.

**Comment by danielkraak** [comment] 2020-01-14 12:42
Thanks for the list. It seems like an audiostreaming issue. I will verify your issues and look into a fix.

**Comment by fille1976** [comment] 2020-01-14 21:00
I will test more games in the next days and report problems here.

**Comment by h3llb3nt** [comment] 2020-01-27 04:10
I have also run into the distorted audio in Mario party 6 and 7.  Was instructed to flip dip switch 4 to go to slower read mode and that has solved the audio issue in those games.

**Comment by fille1976** [comment] 2020-01-27 09:37
Ill wait till they come with an update for it and tested it.

**Comment by fille1976** [comment] 2020-02-15 18:22
Hi daniel,just got swiss v785,still have no sound in menu with wave race in the menu and demo.
Crash bandicoot same problem.
Is there a problem with audio streaming or do i only have this problem?

**Comment by danielkraak** [comment] 2020-02-17 20:50
I will look into it asap. I am currently working on a more fundamental update.

I am 99.9% sure that this is a GC Loader issue and updating Swiss will not help, unfortunately.

**Comment by fille1976** [comment] 2020-02-18 05:49
Ok,take your time daniel. 


Van: "danielkraak" <notifications@github.com> 
Aan: "danielkraak/GC-Loader" <GC-Loader@noreply.github.com> 
Cc: "f meyers" <f.meyers@telenet.be>, "Comment" <comment@noreply.github.com> 
Verzonden: Maandag 17 februari 2020 21:50:13 
Onderwerp: Re: [danielkraak/GC-Loader] Distorted Audio in 1.0.0 (#1) 



I will look into it asap. I am currently working on a more fundamental update. 

I am 99.9% sure that this is a GC Loader issue and updating Swiss will not help, unfortunately.

**Comment by retrofank** [comment] 2020-02-19 12:00
Waverace has given me no issues so far with any audio problems in-game, menus, character selection, but I can confirm the problem with Super Monkey Ball that the OP reported occured for me too after competing the first 10 levels.  However, music plays on the demo (press start screen) for me.

In addition, Eternal Darkness had some distorted audio when left on the demo loop for several minutes, which corrected itself.

NTSC/J console
USA Redump set (full isos)
256gb Sandisk SD card

**Comment by fille1976** [comment] 2020-02-19 18:31
My source for games is redump full iso's.

**Comment by fille1976** [comment] 2020-05-01 10:13
Since i hat contact with daniel i can say my problem is solved,it was the flex cable.
Soldered new one in and now i can fully enjoy my gcloader.
I tested as many games as possible,no problems found.
Thx again to daniel for his fantastic feedback.

**Comment by danielkraak** [comment] 2020-05-05 07:08
I was able to reproduce the issue in Wave Race. It seems when an audio stream is started, there is a very small chance that the audio is distorted. The cause is currently under investigation.

**Comment by etsuna2345** [comment] 2020-07-04 10:38
Hi, yes thé audio si distorded sometimes When an audio is starter.
For ex Extrême G3, crazy taxi, Mario party 7.

**Comment by danielkraak** [comment] 2021-04-09 14:14
This issue has been fixed in update 1.1.2

**Closed** 2021-04-09 14:14 UTC
